# Generated by Django 2.0.5 on 2018-10-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acproduct',
            name='definitive_food',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='definitive_product',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='prodcut_divisions',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='product_actual_cost',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='product_recipe',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='product_sale_prices',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='product_second_unit',
        ),
        migrations.RemoveField(
            model_name='acproduct',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_child_product',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_parent_product',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_unit',
        ),
        migrations.DeleteModel(
            name='ACProduct',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
