# Generated by Django 2.0.5 on 2018-10-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0003_wasteproduct_wastesale_wastesaleproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastesale',
            options={'verbose_name': 'فروش ضایعات', 'verbose_name_plural': 'فروش های ضایعات'},
        ),
        migrations.AddField(
            model_name='wastesaleproduct',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.WasteSale', verbose_name='فروش'),
            preserve_default=False,
        ),
    ]
