# Generated by Django 2.0.5 on 2018-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0004_auto_20181003_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesale',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='مبلغ فاکتور(ریال)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastesale',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='AmadoWH/static/ChashFactors', verbose_name='فایل رسید'),
        ),
    ]
