# Generated by Django 2.0.5 on 2018-10-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0005_auto_20181003_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesale',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='wastesale',
            name='image',
        ),
    ]
