# Generated by Django 2.0.5 on 2018-10-08 08:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0006_auto_20181003_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.IntegerField(verbose_name='مبلغ')),
                ('cost_date', django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ ثبت قیمت')),
                ('cost_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='توضیح قیمت')),
            ],
            options={
                'verbose_name_plural': 'قیمت ها',
                'verbose_name': 'قیمت',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=64, unique=True, verbose_name='نام پارامتر')),
                ('parameter_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='توضیح پارامتر')),
                ('parameter_is_active', models.BooleanField(default=True, verbose_name='پارامتر فعال است')),
            ],
            options={
                'verbose_name_plural': 'پارامتر ها',
                'verbose_name': 'پارامتر',
            },
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ فروش'),
        ),
    ]
