# Generated by Django 2.1.2 on 2018-10-24 08:06

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0007_auto_20181008_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesaleproduct',
            name='fee',
            field=models.FloatField(default=0, verbose_name='فی(ریال)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=django_jalali.db.models.jDateField(default='1397-08-02', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-08-02', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1397-08-02', verbose_name='تاریخ فروش'),
        ),
    ]
