# Generated by Django 2.1.2 on 2018-10-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0009_auto_20181027_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitiveAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'حساب معین',
                'verbose_name_plural': 'حساب های معین',
            },
        ),
        migrations.CreateModel(
            name='OverAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'حساب کل',
                'verbose_name_plural': 'حساب های کل',
            },
        ),
        migrations.AddField(
            model_name='definitiveaccount',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActualCost.OverAccount', verbose_name='حساب کل'),
        ),
    ]
