# Generated by Django 2.1.2 on 2018-10-28 06:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0010_auto_20181027_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitiveaccount',
            name='parent',
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ فروش'),
        ),
    ]
