# Generated by Django 2.1.2 on 2019-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0119_auto_20190416_1533'),
        ('ActualCost', '0013_auto_20190123_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='فی(ریال)')),
                ('date', django_jalali.db.models.jDateField(default='1398-01-27', verbose_name='تاریخ ثبت قیمت')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.AmadoFood', verbose_name='غذا')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Product', verbose_name='کالا')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Unit', verbose_name='واحد فی')),
            ],
            options={
                'verbose_name': 'قیمت تمام شده',
                'verbose_name_plural': 'قیمت تمام شده ها',
            },
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=django_jalali.db.models.jDateField(default='1398-01-27', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1398-01-27', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1398-01-27', verbose_name='تاریخ فروش'),
        ),
    ]
