# Generated by Django 2.1.2 on 2019-05-05 16:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0014_auto_20190416_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailActualCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.IntegerField(default=0, verbose_name='فی(ریال)')),
            ],
            options={
                'verbose_name': 'جزئیات قیمت تمام شده',
                'verbose_name_plural': 'جزئیات قیمت تمام شده ها',
            },
        ),
        migrations.AlterField(
            model_name='actualcost',
            name='date',
            field=django_jalali.db.models.jDateField(default='1398-02-15', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=django_jalali.db.models.jDateField(default='1398-02-15', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1398-02-15', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1398-02-15', verbose_name='تاریخ فروش'),
        ),
        migrations.AddField(
            model_name='detailactualcost',
            name='actual_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.ActualCost', verbose_name='قیمت تمام شده'),
        ),
        migrations.AddField(
            model_name='detailactualcost',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.Parameter', verbose_name='قیمت تمام شده'),
        ),
    ]
