# Generated by Django 2.1.2 on 2019-05-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0015_auto_20190505_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailactualcost',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='عنوان'),
        ),
    ]
