# Generated by Django 2.1.2 on 2019-05-08 09:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0016_detailactualcost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcost',
            name='from_date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='محاسبه از تاریخ'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='to_date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='محاسبه تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='actualcost',
            name='date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='تاریخ ثبت قیمت'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='wastesale',
            name='sale_date',
            field=django_jalali.db.models.jDateField(default='1398-02-18', verbose_name='تاریخ فروش'),
        ),
    ]
