# Generated by Django 2.1.2 on 2019-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0018_auto_20190616_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailactualcost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='عنوان'),
        ),
    ]
