# Generated by Django 2.0.5 on 2018-07-17 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoWHApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=128, verbose_name='نام بانک')),
                ('bank_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات بانک')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک ها',
                'permissions': (('can_see_bank', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=64, verbose_name='کارت')),
                ('account', models.CharField(max_length=64, verbose_name='شماره حساب')),
                ('shaba', models.CharField(max_length=64, verbose_name='شبا')),
                ('person', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام صاحب حساب')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.Bank', verbose_name='بانک')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب های بانکی',
                'permissions': (('can_see_image', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان پرداخت')),
                ('payment_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات پرداخت')),
                ('payment_due_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ پرداخت')),
                ('payment_cost', models.IntegerField(verbose_name='مبلغ پرداختی(ریال)')),
                ('payment_account', models.CharField(max_length=64, verbose_name='شماره')),
                ('payment_account_type', models.CharField(choices=[('card', 'کارت'), ('account', 'حساب'), ('shaba', 'شبا'), ('pos', 'پوز')], default='card', max_length=64, verbose_name='نوع شماره')),
                ('payment_account_person', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام صاحب شماره')),
                ('payment_add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('payment_confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_pay_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_change_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تغییر')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='registered', max_length=16, verbose_name='وضعیت پرداخت')),
                ('payment_account_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_bank', to='AmadoFinance.Bank', verbose_name='بانک')),
                ('payment_add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
                'permissions': (('can_see_cash', 'می تواند مشاهده کند'), ('can_confirm_cash', 'می تواند تایید کند'), ('can_decline_cash', 'می تواند رد کند'), ('can_pay_cash', 'می تواند پرداخت کند'), ('can_change_status_cash', 'می تواند وضعیت را تغییر دهد')),
            },
        ),
        migrations.CreateModel(
            name='CheckCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=128, verbose_name='نام نوع هزینه')),
                ('cat_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات نوع هزینه')),
            ],
            options={
                'verbose_name': 'نوع هزینه',
                'verbose_name_plural': 'انواع هزینه',
                'permissions': (('can_see_checkcat', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='CheckPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان چک')),
                ('check_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات چک')),
                ('check_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره چک')),
                ('check_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ صدور')),
                ('check_due_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ چک')),
                ('payment_cost', models.IntegerField(verbose_name='مبلغ چک(ریال)')),
                ('check_again_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ مراجعه مجدد به بانک')),
                ('payment_add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('payment_confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_pay_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_change_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تغییر')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده'), ('back', 'برگشت خورده')], default='registered', max_length=16, verbose_name='وضعیت چک')),
                ('check_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caccount_bankc', to='AmadoFinance.Bank', verbose_name='بانک')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک ها',
                'permissions': (('can_see_check', 'می تواند مشاهده کند'), ('can_confirm_check', 'می تواند تایید کند'), ('can_decline_check', 'می تواند رد کند'), ('can_pay_check', 'می تواند پرداخت کند'), ('can_back_check', 'می تواند برگشت بزند'), ('can_change_status_check', 'می تواند وضعیت را تغییر دهد')),
            },
        ),
        migrations.CreateModel(
            name='FactorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('image', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/ChashFactors', verbose_name='فایل تصویر')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='مبلغ فاکتور(ریال)')),
                ('checkp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CheckPayment', verbose_name='چک مربوطه')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CashPayment', verbose_name='پرداخت مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر فاکتور',
                'verbose_name_plural': 'تصاویر فاکتور ها',
                'permissions': (('can_see_image', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان تنخواه')),
                ('payment_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات تنخواه')),
                ('payment_due_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ پرداخت')),
                ('payment_cost', models.IntegerField(verbose_name='مبلغ پرداختی(ریال)')),
                ('payment_account', models.CharField(max_length=64, verbose_name='شماره')),
                ('payment_account_type', models.CharField(blank=True, choices=[('card', 'کارت'), ('account', 'حساب'), ('shaba', 'شبا'), ('pos', 'پوز')], default='card', max_length=64, null=True, verbose_name='نوع شماره')),
                ('payment_account_person', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام صاحب شماره')),
                ('payment_add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('payment_confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_pay_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_change_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تغییر')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده/در انتظار تسویه'), ('closed', 'تسویه شد')], default='registered', max_length=16, verbose_name='وضعیت پرداخت')),
                ('payment_account_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_account_bank', to='AmadoFinance.Bank', verbose_name='بانک')),
                ('payment_add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه ها',
                'permissions': (('can_see_fund', 'می تواند مشاهده کند'), ('can_confirm_fund', 'می تواند تایید کند'), ('can_decline_fund', 'می تواند رد کند'), ('can_pay_fund', 'می تواند پرداخت کند'), ('can_close_fund', 'می تواند تسویه کند'), ('can_change_status_fund', 'می تواند وضعیت را تغییر دهد')),
            },
        ),
        migrations.CreateModel(
            name='InternetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='مبلغ(ریال)')),
            ],
            options={
                'verbose_name': 'فروش اینترنتی',
                'verbose_name_plural': 'فروش های اینترنتی',
                'permissions': (('can_see_website_sale', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='InternetSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام وبسایت')),
            ],
            options={
                'verbose_name': 'وبسایت فروش',
                'verbose_name_plural': 'وبسایت های فروش',
                'permissions': (('can_see_wesite', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=128, verbose_name='نام دسته')),
                ('cat_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات دسته')),
            ],
            options={
                'verbose_name': 'دسته پرداخت',
                'verbose_name_plural': 'دسته های پرداختی',
                'permissions': (('can_see_paycat', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_serial', models.CharField(max_length=128, unique=True, verbose_name='سریال پوز')),
                ('pos_is_mobil', models.BooleanField(default=False, verbose_name='پوز سیار است')),
                ('pos_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AmadoFinance.Bank', verbose_name='بانک پوز')),
                ('pos_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه مربوطه')),
            ],
            options={
                'verbose_name': 'پوز',
                'verbose_name_plural': 'پوز ها',
                'permissions': (('can_see_pos', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='AmadoFinance.Pos', verbose_name='پوز مربوطه')),
            ],
            options={
                'verbose_name': 'فروش پوز',
                'verbose_name_plural': 'فروش های پوز ها',
                'permissions': (('can_see_pos_sale', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='RecedeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('image', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/ChashRecedes', verbose_name='فایل تصویر')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='مبلغ رسید(ریال)')),
                ('checkp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CheckPayment', verbose_name='چک مربوطه')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CashPayment', verbose_name='پرداخت مربوطه')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.FundPayment', verbose_name='تنخواه مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر رسید',
                'verbose_name_plural': 'تصاویر رسید ها',
                'permissions': (('can_see_image', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='RecipientCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=128, verbose_name='نام شرکت گیرنده')),
                ('recipient_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات شرکت')),
            ],
            options={
                'verbose_name': 'گیرنده',
                'verbose_name_plural': 'گیرندگان',
                'permissions': (('can_see_recipientcom', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CashPayment', verbose_name='پرداخت نقدی')),
                ('checkp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CheckPayment', verbose_name='چک')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.FundPayment', verbose_name='تنخواه')),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
                'permissions': (('can_see_relation', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_add_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ ثبت')),
                ('sales_date', django_jalali.db.models.jDateField(default='1397-04-26', verbose_name='تاریخ فروش')),
                ('sales_cash_cost', models.IntegerField(verbose_name='جمع نقدی(ریال)')),
                ('sales_salon', models.IntegerField(verbose_name='تعداد فیش سالن')),
                ('sales_delivery', models.IntegerField(verbose_name='تعداد فیش دلیوری')),
                ('sales_salon_cancel', models.IntegerField(verbose_name='تعداد فیش  کنسلی سالن')),
                ('sales_delivery_cancel', models.IntegerField(verbose_name='تعداد فیش کنسلی دلیوری')),
                ('sales_tot_cash_cost', models.IntegerField(verbose_name='کل مبلغ فروش(ریال)')),
                ('sales_delivery_cost', models.IntegerField(verbose_name='مبلغ دلیوری(ریال)')),
                ('sales_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه مربوطه')),
                ('sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
                'permissions': (('can_see_sales', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='AmadoFinance.Sales', verbose_name='فروش مربوطه'),
        ),
        migrations.AddField(
            model_name='internetsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsale', to='AmadoFinance.Sales', verbose_name='فروش مربوطه'),
        ),
        migrations.AddField(
            model_name='internetsale',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='AmadoFinance.InternetSeller', verbose_name='سایت'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='payment_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.PaymentCategory', verbose_name='بابت'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='payment_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fun_change_user', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='payment_confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='payment_pay_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_pay_user', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='payment_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='گیرنده'),
        ),
        migrations.AddField(
            model_name='factorimage',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.FundPayment', verbose_name='تنخواه مربوطه'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='check_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.PaymentCategory', verbose_name='بابت'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='check_payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CheckCategory', verbose_name='نوع هزینه'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='check_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='دریافت کننده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='payment_add_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cregister_userc', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='payment_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cchange_userc', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='payment_confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cconfirm_userc', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='payment_pay_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpay_userc', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Supplier', verbose_name='تامین کننده'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.PaymentCategory', verbose_name='بابت'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_pay_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_user', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='گیرنده'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Supplier', verbose_name='تامین کننده'),
        ),
        migrations.AlterUniqueTogether(
            name='possale',
            unique_together={('pos', 'sale')},
        ),
        migrations.AlterUniqueTogether(
            name='internetsale',
            unique_together={('website', 'sale')},
        ),
    ]
