# Generated by Django 2.0.5 on 2018-08-06 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoFinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'permissions': (('can_see_sales', 'می تواند مشاهده کند'), ('can_close_sales', 'می تواند ببندد'), ('can_edit_sales', 'می تواند ویرایش کند')), 'verbose_name': 'فروش', 'verbose_name_plural': 'فروش ها'},
        ),
        migrations.AddField(
            model_name='relationship',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.ShopRequest', verbose_name='خرید'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_change_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_user', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_close_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_close_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closes_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_status',
            field=models.CharField(choices=[('registered', 'ثبت شده'), ('closed', 'بسته شده'), ('changed', 'تغییر کرده'), ('tryagain', 'نیاز به بررسی')], default='registered', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_try_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ رد'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_try_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='try_user', to=settings.AUTH_USER_MODEL, verbose_name='رد کننده'),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ فروش'),
        ),
    ]
