# Generated by Django 2.0.5 on 2018-08-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0005_auto_20180813_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='payment_cost',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='payment_description',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='payment_recipient',
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AmadoFinance.Payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='گیرنده'),
            preserve_default=False,
        ),
    ]
