# Generated by Django 2.0.5 on 2018-08-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0007_remove_payment_payment_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='گیرنده'),
            preserve_default=False,
        ),
    ]
