# Generated by Django 2.0.5 on 2018-08-13 07:10

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0008_payment_payment_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_recipient',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='payment_ptr',
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_cost',
            field=models.IntegerField(default=1, verbose_name='مبلغ پرداختی(ریال)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات پرداخت'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-05-22', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='payment_recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.RecipientCompany', verbose_name='گیرنده'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
