# Generated by Django 2.0.5 on 2018-09-19 06:01

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0050_auto_20180919_1031'),
        ('AmadoFinance', '0018_auto_20180914_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='recedeimage',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.SalaryDetail', verbose_name='حقوق مربوطه'),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-06-28', verbose_name='تاریخ فروش'),
        ),
    ]
