# Generated by Django 2.0.5 on 2018-09-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0021_auto_20180930_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='cost_center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CostCenter', verbose_name='مرکز هزینه'),
            preserve_default=False,
        ),
    ]
