# Generated by Django 2.0.5 on 2018-09-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0023_auto_20180930_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcenter',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='fundpayment',
            name='cost_center',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
