# Generated by Django 2.0.5 on 2018-09-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0088_auto_20180930_1328'),
        ('AmadoFinance', '0024_auto_20180930_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AmadoWHApp.Branch')),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'verbose_name_plural': 'مراکز هزینه',
            },
        ),
    ]
