# Generated by Django 2.0.5 on 2018-09-30 10:07

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0025_costcenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpayment',
            options={'permissions': (('can_see_cash', 'می تواند مشاهده کند'), ('can_confirm_cash', 'می تواند تایید کند'), ('can_decline_cash', 'می تواند رد کند'), ('can_pay_cash', 'می تواند پرداخت کند'), ('can_change_status_cash', 'می تواند وضعیت را تغییر دهد')), 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت به تامین کنندگان'},
        ),
        migrations.AlterModelOptions(
            name='fundpayment',
            options={'permissions': (('can_see_fund', 'می تواند مشاهده کند'), ('can_confirm_fund', 'می تواند تایید کند'), ('can_decline_fund', 'می تواند رد کند'), ('can_pay_fund', 'می تواند پرداخت کند'), ('can_close_fund', 'می تواند تسویه کند'), ('can_change_status_fund', 'می تواند وضعیت را تغییر دهد')), 'verbose_name': 'تنخواه / صبحانه', 'verbose_name_plural': 'تنخواه ها / صبحانه ها'},
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='cost_center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CostCenter', verbose_name='مرکز هزینه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.PaymentCategory', verbose_name='بابت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='payment_status',
            field=models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده'), ('back', 'برگشت خورده')], default='confirmed', max_length=16, verbose_name='وضعیت چک'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AmadoWHApp.Branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(verbose_name='مبلغ رسید(ریال)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='checkp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CheckPayment', verbose_name='چک/نقد'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_change_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-06-31 00:09:00.000000', verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_close_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-06-31 00:09:00.000000', verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_try_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-06-31 00:09:00.000000', verbose_name='تاریخ رد'),
        ),
    ]
