# Generated by Django 2.0.5 on 2018-09-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0027_auto_20180930_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetsale',
            name='test',
        ),
    ]
