# Generated by Django 2.0.5 on 2018-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0028_remove_internetsale_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetsale',
            name='test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
