# Generated by Django 2.0.5 on 2018-09-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0029_internetsale_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetsale',
            name='test',
        ),
    ]
