# Generated by Django 2.0.5 on 2018-10-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0006_auto_20181003_1538'),
        ('AmadoFinance', '0031_auto_20181003_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorimage',
            name='sell_waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.WasteSale', verbose_name=''),
        ),
        migrations.AddField(
            model_name='recedeimage',
            name='waste_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.WasteSale', verbose_name='فروش ضایعات'),
        ),
    ]
