# Generated by Django 2.0.5 on 2018-10-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0032_auto_20181003_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorimage',
            name='sell_waste',
        ),
    ]
