# Generated by Django 2.0.5 on 2018-10-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0033_remove_factorimage_sell_waste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recedeimage',
            name='waste_sell',
        ),
    ]
