# Generated by Django 2.0.5 on 2018-10-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0006_auto_20181003_1538'),
        ('AmadoFinance', '0034_remove_recedeimage_waste_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='recedeimage',
            name='waste_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ActualCost.WasteSale', verbose_name='فروش ضایعات'),
        ),
    ]
