# Generated by Django 2.0.5 on 2018-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0035_recedeimage_waste_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
