# Generated by Django 2.0.5 on 2018-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0036_auto_20181003_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
