# Generated by Django 2.1.2 on 2018-10-25 08:44

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0037_auto_20181003_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_delivery_cancel_cost',
            field=models.IntegerField(default=0, verbose_name='جمع مبلغ فیش کنسلی دلیوری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_salon_cancel_cost',
            field=models.IntegerField(default=0, verbose_name='جمع مبلغ کنسلی سالن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_status',
            field=models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده/در انتظار تسویه')], default='registered', max_length=16, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(verbose_name='مبلغ رسید(ریال)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-08-03', verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_status',
            field=models.CharField(choices=[('registered', 'ثبت شده'), ('closed', 'بسته شده'), ('changed', 'تغییر کرده'), ('tryagain', 'نیاز به بررسی')], default='closed', max_length=16, verbose_name='وضعیت'),
        ),
    ]
