# Generated by Django 2.1.2 on 2018-10-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0038_auto_20181025_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_salon_cancel_cost',
        ),
    ]
