# Generated by Django 2.1.2 on 2018-10-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0039_remove_sales_sales_salon_cancel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_salon_cancel_cost',
            field=models.IntegerField(default=0, verbose_name='جمع مبلغ کنسلی سالن'),
            preserve_default=False,
        ),
    ]
