# Generated by Django 2.1.2 on 2018-10-28 07:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0011_auto_20181028_1029'),
        ('AmadoFinance', '0040_sales_sales_salon_cancel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='def_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='defacash', to='ActualCost.OverAccount', verbose_name='حساب معین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='over_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='overcash', to='ActualCost.OverAccount', verbose_name='حساب کل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-08-06', verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_delivery_cancel',
            field=models.IntegerField(verbose_name='تعداد فیش حذفی دلیوری'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_delivery_cancel_cost',
            field=models.IntegerField(verbose_name='جمع مبلغ فیش حذفی دلیوری'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_salon_cancel',
            field=models.IntegerField(verbose_name='تعداد فیش  حذفی سالن'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_salon_cancel_cost',
            field=models.IntegerField(verbose_name='جمع مبلغ حذفی سالن'),
        ),
    ]
