# Generated by Django 2.1.2 on 2018-10-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActualCost', '0011_auto_20181028_1029'),
        ('AmadoFinance', '0041_auto_20181028_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='fundpayment',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='def_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='defacheck', to='ActualCost.OverAccount', verbose_name='حساب معین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='over_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='overccheck', to='ActualCost.OverAccount', verbose_name='حساب کل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='def_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='defafund', to='ActualCost.OverAccount', verbose_name='حساب معین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='over_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='overcfund', to='ActualCost.OverAccount', verbose_name='حساب کل'),
            preserve_default=False,
        ),
    ]
