# Generated by Django 2.1.2 on 2018-10-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0042_auto_20181028_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='def_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defacash', to='AmadoWHApp.Branch', verbose_name='حساب معین'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='def_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defacheck', to='AmadoWHApp.Branch', verbose_name='حساب معین'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='def_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defafund', to='AmadoWHApp.Branch', verbose_name='حساب معین'),
        ),
    ]
