# Generated by Django 2.1.2 on 2018-10-29 06:38

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0043_auto_20181028_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='def_account',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='def_account',
        ),
        migrations.RemoveField(
            model_name='fundpayment',
            name='def_account',
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='cost_center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='costccash', to='AmadoFinance.CostCenter', verbose_name='مرکز هزینه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='cost_center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CostCenter', verbose_name='مرکز هزینه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='cost_center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.CostCenter', verbose_name='مرکز هزینه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ فروش'),
        ),
    ]
