# Generated by Django 2.1.2 on 2018-10-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0044_auto_20181029_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcenter',
            name='branch',
        ),
    ]
