# Generated by Django 2.1.2 on 2018-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0048_recedeimage_def_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
