# Generated by Django 2.1.2 on 2018-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0051_recedeimage_def_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recedeimage',
            name='def_account',
        ),
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
