# Generated by Django 2.1.2 on 2018-12-07 07:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0053_recedeimage_def_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='pos_is_active',
            field=models.BooleanField(default=True, verbose_name='پوز فعال است'),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_again_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ مراجعه مجدد به بانک'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='check_due_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(verbose_name='مبلغ رسید(ریال)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_add_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=django_jalali.db.models.jDateField(default='1397-09-16', verbose_name='تاریخ فروش'),
        ),
    ]
