# Generated by Django 2.1.2 on 2018-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0054_auto_20181207_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
