# Generated by Django 2.1.2 on 2018-12-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0055_auto_20181207_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='pos_is_active',
        ),
    ]
