# Generated by Django 2.1.2 on 2018-12-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0056_remove_pos_pos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='pos_is_active',
            field=models.BooleanField(default=True, verbose_name='پوز فعال است'),
        ),
    ]
