# Generated by Django 2.1.2 on 2019-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0059_auto_20190123_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
