# Generated by Django 2.1.2 on 2019-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0064_auto_20190123_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recedeimage',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ رسید(ریال)'),
        ),
    ]
