# Generated by Django 2.1.2 on 2019-01-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0065_auto_20190123_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recedeimage',
            name='payment_due_date',
        ),
    ]
