# Generated by Django 2.1.2 on 2019-01-23 12:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0066_remove_recedeimage_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recedeimage',
            name='payment_due_date',
            field=django_jalali.db.models.jDateField(default='1397-11-03', verbose_name='تاریخ'),
        ),
    ]
