# Generated by Django 2.0.5 on 2018-08-06 08:10

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0002_auto_20180806_1240'),
        ('AmadoWHApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='قیمت')),
                ('date', django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ قیمت')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.AlterModelOptions(
            name='shoprequest',
            options={'permissions': (('can_see_shopreq', 'می تواند مشاهده کند'), ('can_confirm_shopreq', 'می تواند تایید کند')), 'verbose_name': 'خرید و ورود به انبار', 'verbose_name_plural': 'خرید ها و ورود به انبار'},
        ),
        migrations.AlterModelOptions(
            name='showhelpticket',
            options={'verbose_name_plural': 'Help Tickets ( 9unclosed )'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_actual_price_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تمام شده نوع ۱'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_actual_price_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تمام شده نوع ۲'),
        ),
        migrations.AddField(
            model_name='product',
            name='report_index',
            field=models.IntegerField(default=-1, verbose_name='ردیف در گزارش'),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='request_amount_sent',
            field=models.FloatField(blank=True, null=True, verbose_name='میزان دریافتی از انبار'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_account',
            field=models.ManyToManyField(to='AmadoFinance.BankAccount', verbose_name='حساب بانکی تامین کننده'),
        ),
        migrations.AlterField(
            model_name='amadofood',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='branchwarehouse',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ موجودی'),
        ),
        migrations.AlterField(
            model_name='foodsale',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.CharField(blank=True, default='1397-05-15 ساعت 12:40', max_length=32, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-05-15', null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:40:53', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-05-15', null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:40:53', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-05-15', null=True, verbose_name='تاریخ ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:40:53', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='last_price_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='rc_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ دریافت'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='from_date',
            field=django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ خرید'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Product', verbose_name='محصول مربوطه'),
        ),
    ]
