# Generated by Django 2.0.5 on 2018-08-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0005_auto_20180806_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='report_index',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:42:58', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:42:58', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:42:58', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
    ]
