# Generated by Django 2.0.5 on 2018-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0011_auto_20180806_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:19', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:19', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:19', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
    ]
