# Generated by Django 2.0.5 on 2018-08-06 08:15

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0013_auto_20180806_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='قیمت')),
                ('date', django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:46', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:46', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:45:46', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
    ]
