# Generated by Django 2.0.5 on 2018-08-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0018_auto_20180806_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='request_amount_sent',
            field=models.FloatField(blank=True, null=True, verbose_name='میزان دریافتی از انبار'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:49:45', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:49:45', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:49:45', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
    ]
