# Generated by Django 2.0.5 on 2018-08-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoWHApp', '0022_auto_20180812_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchwarehouse',
            name='confirm_date',
            field=django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='branchwarehouse',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmbw', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='branchwarehouse',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده')], default='registered', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.CharField(blank=True, default='1397-05-21 ساعت 19:03', max_length=32, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='19:03:51', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='19:03:51', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='19:03:51', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
    ]
