# Generated by Django 2.0.5 on 2018-09-14 06:55

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0078_auto_20180911_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_amount', models.FloatField(verbose_name='میزان ماده تشکیل دهنده در ۱ واحد از محصول')),
            ],
            options={
                'verbose_name': 'ترکیبات غذا',
                'verbose_name_plural': 'ترکیبات غذاها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_second_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sec_unit', to='AmadoWHApp.Unit', verbose_name='واحد محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_ratio',
            field=models.FloatField(default=1, verbose_name='واحد ۱ دارای این مقدار از واحد ۲ است'),
        ),
        migrations.AlterField(
            model_name='amadofood',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='branchwarehouse',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ موجودی'),
        ),
        migrations.AlterField(
            model_name='foodsale',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.CharField(blank=True, default='1397-06-23 ساعت 11:25', max_length=32, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-06-23', null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='11:25:21', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-06-23', null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='11:25:21', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-06-23', null=True, verbose_name='تاریخ ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='11:25:21', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='last_price_date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='rc_date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ دریافت'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='from_date',
            field=django_jalali.db.models.jDateField(default='1397-06-23', verbose_name='تاریخ خرید'),
        ),
        migrations.AddField(
            model_name='foodcombinations',
            name='recipe_child_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='AmadoWHApp.AmadoFood', verbose_name='محصول نهایی'),
        ),
        migrations.AddField(
            model_name='foodcombinations',
            name='recipe_parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='AmadoWHApp.Product', verbose_name='ماده تشکیل دهنده'),
        ),
        migrations.AddField(
            model_name='foodcombinations',
            name='recipe_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Unit', verbose_name='واحد مقدار'),
        ),
    ]
