# Generated by Django 2.0.5 on 2018-09-30 16:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0088_auto_20180930_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcombinations',
            name='recipe_child_product',
        ),
        migrations.RemoveField(
            model_name='foodcombinations',
            name='recipe_parent_product',
        ),
        migrations.RemoveField(
            model_name='foodcombinations',
            name='recipe_unit',
        ),
        migrations.AlterModelOptions(
            name='branchwarehouse',
            options={'permissions': (('can_see_brawar', 'می تواند مشاهده کند'),), 'verbose_name': 'موجودی انبار شعبه', 'verbose_name_plural': 'موجودی انبار شعب'},
        ),
        migrations.AlterField(
            model_name='foodsaleproduct',
            name='amount',
            field=models.IntegerField(verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.CharField(blank=True, default='1397-07-08 ساعت 20:06', max_length=32, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='20:06:56', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='20:06:56', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='20:06:56', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='amount',
            field=models.FloatField(default=0, verbose_name='میزان خرید'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='last_price',
            field=models.IntegerField(verbose_name='فی(ریال)'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='last_price_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-07-08', null=True, verbose_name='تاریخ آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='purchase_durability',
            field=models.IntegerField(default=0, verbose_name='ماندگاری خرید(روز)'),
        ),
        migrations.DeleteModel(
            name='FoodCombinations',
        ),
    ]
