# Generated by Django 2.0.5 on 2018-10-08 08:57

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0055_auto_20181008_1227'),
        ('ActualCost', '0007_auto_20181008_1140'),
        ('AmadoWHApp', '0092_auto_20181003_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='نام محصول')),
                ('product_process', models.CharField(choices=[('dried', 'خشک'), ('wet_p', 'تر فرآوری شده'), ('wet_np', 'تر فرآوری نشده')], default='dried', max_length=16, verbose_name='فرآوری محصول')),
                ('product_price_parameter', models.IntegerField(default=1, verbose_name='چندمین بزرگترین قیمت')),
                ('product_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات محصول')),
                ('product_weekly_consumption', models.FloatField(default=0, verbose_name='مصرف هفتگی')),
                ('product_is_active', models.BooleanField(default=False, verbose_name='کالا فعال می باشد')),
                ('product_monthly_storage', models.FloatField(default=0, verbose_name='ماندگاری محصول(بر اساس ماه)')),
                ('parameters', models.ManyToManyField(blank=True, null=True, to='ActualCost.Parameter', verbose_name='پارامتر های قیمت تمام شده')),
                ('prodcut_divisions', models.ManyToManyField(blank=True, null=True, to='AmadoAccounting.Division', verbose_name='بخش های مربوطه')),
                ('product_actual_cost', models.ManyToManyField(blank=True, null=True, related_name='actual_cost', to='ActualCost.Cost', verbose_name='قیمت تمام شده ها')),
                ('product_sale_prices', models.ManyToManyField(blank=True, null=True, related_name='sale_price', to='ActualCost.Cost', verbose_name='قیمت فروش')),
            ],
            options={
                'verbose_name_plural': 'کالاهای قابل خرید',
                'verbose_name': 'کالای قابل خرید',
            },
        ),
        migrations.AlterField(
            model_name='amadofood',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='branchwarehouse',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ موجودی'),
        ),
        migrations.AlterField(
            model_name='foodsale',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.CharField(blank=True, default='1397-07-16 ساعت 12:27', max_length=32, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_change_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ تغییر قیمت'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-07-16', null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(blank=True, default='12:27:36', null=True, verbose_name='ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-07-16', null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='request_time',
            field=models.TimeField(blank=True, default='12:27:36', null=True, verbose_name='ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-07-16', null=True, verbose_name='تاریخ ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='requestproductvariance',
            name='request_time',
            field=models.TimeField(blank=True, default='12:27:36', null=True, verbose_name='ساعت ثبت مغایرت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='last_price_date',
            field=django_jalali.db.models.jDateField(blank=True, default='1397-07-16', null=True, verbose_name='تاریخ آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='rc_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ دریافت'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='from_date',
            field=django_jalali.db.models.jDateField(default='1397-07-16', verbose_name='تاریخ خرید'),
        ),
    ]
