# Generated by Django 2.0.5 on 2018-08-06 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0001_initial'),
        ('AmadoWHApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoAccounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام')),
                ('image', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/Staff/Picture', verbose_name='عکس پرسنلی')),
                ('kart_melli', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/Staff/ID', verbose_name='کارت ملی و شناسنامه')),
                ('behdasht', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/Staff/Health', verbose_name='کارت بهداشت')),
                ('sooepishine', models.FileField(blank=True, null=True, upload_to='AmadoWH/static/Staff/Sooepishine', verbose_name='گواهی عدم سوء پیشینه')),
                ('banks', models.ManyToManyField(blank=True, null=True, related_name='pbankp', to='AmadoFinance.BankAccount', verbose_name='حساب های فرد')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
                'permissions': (('can_see_person', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('branch', models.ManyToManyField(to='AmadoWHApp.Branch', verbose_name='شعبه مربوطه')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Division', verbose_name='بخش مربوطه')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
                'permissions': (('can_see_role', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('finish_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Role', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'تاریخچه نقش',
                'verbose_name_plural': 'تاریخچه ها',
                'permissions': (('can_see_rolehistory', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', django_jalali.db.models.jDateField(verbose_name='ماه')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده')], default='registered', max_length=16, verbose_name='وضعیت')),
                ('add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق ها',
                'permissions': (('can_see_salary', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(verbose_name='حقوق پایه وزارت کار')),
                ('base_on_2_shift', models.BooleanField(default=True, verbose_name='حقوق پایه براساس ۲ شیبف می باشد')),
                ('days', models.IntegerField(verbose_name='تعداد روزهای کارکرد')),
                ('fix', models.IntegerField(verbose_name='حقوق ثابت')),
                ('extra_shift', models.IntegerField(verbose_name='شیفت اضافه')),
                ('off', models.IntegerField(verbose_name='ایام تعطیل کاری')),
                ('maskan_base', models.IntegerField(default=400000, verbose_name='پایه حق مسکن')),
                ('childs', models.IntegerField(verbose_name='تعداد فرزند')),
                ('bon_base', models.IntegerField(default=1100000, verbose_name='پایه حق بن')),
                ('mazaya', models.IntegerField(verbose_name='مزایای شغلی')),
                ('week_base', models.IntegerField(default=220, verbose_name='حداقل ساعات کار ماهانه')),
                ('extra_percentage', models.FloatField(default=1.4, verbose_name='درصد اضافه کاری')),
                ('extra_hours', models.FloatField(verbose_name='ساعت اضافه کاری')),
                ('help', models.IntegerField(verbose_name='مساعده')),
                ('bime_percentage', models.FloatField(default=7, verbose_name='درصد بیمه')),
                ('tax_min', models.IntegerField(verbose_name='حداقل پایه حقوق برای محاسبه مالیات')),
                ('tax_bime_ratio', models.FloatField(default=0.28571429, verbose_name='کسر بیمه مالیات')),
                ('tax_percentage', models.IntegerField(default=10, verbose_name='درصد مالیات')),
                ('kargar_bime_ratio1', models.FloatField(default=23, verbose_name='درصد حق کارگر در بیمه')),
                ('if_delivery_count', models.IntegerField(verbose_name='تعداد دلیوری')),
                ('if_delivery_base', models.IntegerField(verbose_name='پایه حق سرویس دلیوری')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده'), ('paid', 'پرداخت شده'), ('pending', 'درانتظار پرداخت'), ('error', 'نقص مدارک')], default='registered', max_length=16, verbose_name='وضعیت حقوقی')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Salary', verbose_name='پرونده حقوق مربوطه')),
            ],
            options={
                'verbose_name': 'جزئیات حقوق',
                'verbose_name_plural': 'جزئیات حقوق ها',
                'permissions': (('can_see_salary_det', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default='1397-05-15', verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده')], default='registered', max_length=16, verbose_name='وضعیت')),
                ('add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
            ],
            options={
                'verbose_name': 'کارکرد',
                'verbose_name_plural': 'کارکرد ها',
                'permissions': (('can_see_work', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(choices=[('P', 'حضور یک شیفت'), ('PP', 'حضور دو شیفت'), ('V', 'مرخصی'), ('T', 'ترانسفر'), ('O', 'آف'), ('A', 'غیبت')], default='P', max_length=16, verbose_name='وضعیت حضور')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Work', verbose_name='پرونده کارکرد مربوطه')),
            ],
            options={
                'verbose_name': 'جزئیات کارکرد',
                'verbose_name_plural': 'جزئیات کارکرد ها',
                'permissions': (('can_see_work_det', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='workdetail',
            unique_together={('person', 'work')},
        ),
        migrations.AlterUniqueTogether(
            name='salarydetail',
            unique_together={('person', 'salary')},
        ),
    ]
