# Generated by Django 2.0.5 on 2018-08-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0002_auto_20180806_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='base_on_2_shift',
        ),
    ]
