# Generated by Django 2.0.5 on 2018-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0003_remove_salarydetail_base_on_2_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='base_on_2_shift',
            field=models.BooleanField(default=True, verbose_name='حقوق پایه براساس ۲ شیبف می باشد'),
        ),
    ]
