# Generated by Django 2.0.5 on 2018-08-11 11:55

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0004_salarydetail_base_on_2_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='two_shift',
            field=models.BooleanField(default=True, verbose_name='حضور دو شیفت'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-20', verbose_name='تاریخ'),
        ),
    ]
