# Generated by Django 2.0.5 on 2018-08-12 13:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0005_auto_20180811_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='two_shift',
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-21', verbose_name='تاریخ'),
        ),
    ]
