# Generated by Django 2.0.5 on 2018-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0006_auto_20180812_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='two_shift',
            field=models.BooleanField(default=True, verbose_name='حضور دو شیفت'),
        ),
    ]
