# Generated by Django 2.0.5 on 2018-08-13 07:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0007_person_two_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-22', verbose_name='تاریخ'),
        ),
    ]
