# Generated by Django 2.0.5 on 2018-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0009_auto_20180821_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='off',
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='if_delivery_base',
            field=models.IntegerField(default=10000, verbose_name='پایه حق سرویس دلیوری'),
        ),
    ]
