# Generated by Django 2.0.5 on 2018-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0010_auto_20180821_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='year_days',
            field=models.IntegerField(default=365, verbose_name='تعداد روزهای سال'),
        ),
    ]
