# Generated by Django 2.0.5 on 2018-08-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0011_salarydetail_year_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='vezarat_kar_base',
            field=models.IntegerField(default=11112690, verbose_name='حقوق پایه وزارت کار'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='base',
            field=models.IntegerField(default=11112690, verbose_name='حقوق ثابت'),
        ),
    ]
