# Generated by Django 2.0.5 on 2018-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0012_auto_20180821_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='reward',
            field=models.IntegerField(default=0, verbose_name='پاداش'),
            preserve_default=False,
        ),
    ]
