# Generated by Django 2.0.5 on 2018-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0013_salarydetail_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='other_deductions',
            field=models.IntegerField(default=0, verbose_name='سایر کسورات'),
            preserve_default=False,
        ),
    ]
