# Generated by Django 2.0.5 on 2018-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0014_salarydetail_other_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='penalty',
            field=models.IntegerField(default=0, verbose_name='جریمه'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='help',
            field=models.IntegerField(default=0, verbose_name='مساعده'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='mazaya',
            field=models.IntegerField(default=0, verbose_name='مزایای شغلی'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='other_deductions',
            field=models.IntegerField(default=0, verbose_name='سایر کسورات'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='reward',
            field=models.IntegerField(default=0, verbose_name='پاداش'),
        ),
    ]
