# Generated by Django 2.0.5 on 2018-08-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0015_auto_20180821_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='bime_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bon_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='extra_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='kargar_bime_ratio1',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='maskan_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_bime_ratio',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='week_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='year_days',
        ),
        migrations.AddField(
            model_name='salary',
            name='bime_percentage',
            field=models.FloatField(default=7, verbose_name='درصد بیمه'),
        ),
        migrations.AddField(
            model_name='salary',
            name='bon_base',
            field=models.IntegerField(default=1100000, verbose_name='پایه حق بن'),
        ),
        migrations.AddField(
            model_name='salary',
            name='extra_percentage',
            field=models.FloatField(default=1.4, verbose_name='درصد اضافه کاری'),
        ),
        migrations.AddField(
            model_name='salary',
            name='kargar_bime_ratio1',
            field=models.FloatField(default=23, verbose_name='درصد حق کارگر در بیمه'),
        ),
        migrations.AddField(
            model_name='salary',
            name='maskan_base',
            field=models.IntegerField(default=400000, verbose_name='پایه حق مسکن'),
        ),
        migrations.AddField(
            model_name='salary',
            name='tax_bime_ratio',
            field=models.FloatField(default=0.28571429, verbose_name='کسر بیمه مالیات'),
        ),
        migrations.AddField(
            model_name='salary',
            name='tax_percentage',
            field=models.IntegerField(default=10, verbose_name='درصد مالیات'),
        ),
        migrations.AddField(
            model_name='salary',
            name='week_base',
            field=models.IntegerField(default=220, verbose_name='حداقل ساعات کار ماهانه'),
        ),
        migrations.AddField(
            model_name='salary',
            name='year_days',
            field=models.IntegerField(default=365, verbose_name='تعداد روزهای سال'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bime_fee',
            field=models.IntegerField(default=0, verbose_name='سنوات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bon_fee',
            field=models.IntegerField(default=0, verbose_name='بن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='childs_fee',
            field=models.IntegerField(default=0, verbose_name='حق اولاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='delivery_fee',
            field=models.IntegerField(default=0, verbose_name='حق پیک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='extra_hour_fee',
            field=models.IntegerField(default=0, verbose_name='مبلغ اضافه کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='extra_shift_fee',
            field=models.IntegerField(default=0, verbose_name='مزد شیفت اضافه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='karfarma_bime_share',
            field=models.IntegerField(default=0, verbose_name='بیمه حق کارفرما'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='maskan_fee',
            field=models.IntegerField(default=0, verbose_name='حق مسکن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='off_days',
            field=models.IntegerField(default=0, verbose_name='ایام تعطیل کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='off_days_fee',
            field=models.IntegerField(default=0, verbose_name='مبلغ تعطیل کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='payable_salary',
            field=models.IntegerField(default=0, verbose_name='حقوق پرداختنی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='salary_plus_mazaya',
            field=models.IntegerField(default=0, verbose_name='جمع حقوق و مزایا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='tax_fee',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='total_deduction',
            field=models.IntegerField(default=0, verbose_name='جمع کسورات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='work_days',
            field=models.IntegerField(default=0, verbose_name='تعداد روز های کارکرد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='years_fee',
            field=models.IntegerField(default=0, verbose_name='سنوات'),
            preserve_default=False,
        ),
    ]
