# Generated by Django 2.0.5 on 2018-08-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0010_auto_20180821_1054'),
        ('AmadoAccounting', '0017_auto_20180821_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='bank_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.BankAccount', verbose_name='حساب بانکی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax_min',
            field=models.IntegerField(default=23000000, verbose_name='حداقل پایه حقوق برای محاسبه مالیات'),
        ),
    ]
