# Generated by Django 2.0.5 on 2018-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0018_auto_20180821_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='description',
            field=models.TextField(default=0, max_length=128, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
