# Generated by Django 2.0.5 on 2018-09-01 07:35

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0019_salarydetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='delivery_fee',
            field=models.IntegerField(verbose_name='حق پیک/سالاد'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='if_delivery_base',
            field=models.IntegerField(default=10000, verbose_name='پایه حق سرویس دلیوری/سالاد'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='if_delivery_count',
            field=models.IntegerField(verbose_name='تعداد دلیوری/سالاد'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-10', verbose_name='تاریخ'),
        ),
    ]
