# Generated by Django 2.0.5 on 2018-09-01 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoFinance', '0011_auto_20180901_1205'),
        ('AmadoWHApp', '0048_auto_20180901_1209'),
        ('AmadoAccounting', '0021_auto_20180901_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', django_jalali.db.models.jDateField(verbose_name='ماه')),
                ('vezarat_kar_base', models.IntegerField(default=11112690, verbose_name='حقوق پایه وزارت کار')),
                ('maskan_base', models.IntegerField(default=400000, verbose_name='پایه حق مسکن')),
                ('bon_base', models.IntegerField(default=1100000, verbose_name='پایه حق بن')),
                ('year_days', models.IntegerField(default=365, verbose_name='تعداد روزهای سال')),
                ('week_base', models.IntegerField(default=220, verbose_name='حداقل ساعات کار ماهانه')),
                ('extra_percentage', models.FloatField(default=1.4, verbose_name='درصد اضافه کاری')),
                ('bime_percentage', models.FloatField(default=7, verbose_name='درصد بیمه')),
                ('tax_bime_ratio', models.FloatField(default=0.28571429, verbose_name='کسر بیمه مالیات')),
                ('tax_percentage', models.IntegerField(default=10, verbose_name='درصد مالیات')),
                ('kargar_bime_ratio1', models.FloatField(default=23, verbose_name='درصد حق کارگر در بیمه')),
                ('tax_min', models.IntegerField(default=23000000, verbose_name='حداقل پایه حقوق برای محاسبه مالیات')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده')], default='registered', max_length=16, verbose_name='وضعیت')),
                ('add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق ها',
                'permissions': (('can_see_salary', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(default=11112690, verbose_name='حقوق ثابت')),
                ('base_on_2_shift', models.BooleanField(default=True, verbose_name='حقوق پایه براساس ۲ شیبف می باشد')),
                ('fix', models.IntegerField(verbose_name='حقوق پایه')),
                ('extra_shift', models.IntegerField(verbose_name='شیفت اضافه')),
                ('childs', models.IntegerField(verbose_name='تعداد فرزند')),
                ('mazaya', models.IntegerField(default=0, verbose_name='مزایای شغلی')),
                ('extra_hours', models.FloatField(verbose_name='ساعت اضافه کاری')),
                ('reward', models.IntegerField(default=0, verbose_name='پاداش')),
                ('help', models.IntegerField(default=0, verbose_name='مساعده')),
                ('other_deductions', models.IntegerField(default=0, verbose_name='سایر کسورات')),
                ('penalty', models.IntegerField(default=0, verbose_name='جریمه')),
                ('if_delivery_count', models.IntegerField(verbose_name='تعداد دلیوری/سالاد')),
                ('if_delivery_base', models.IntegerField(default=10000, verbose_name='پایه حق سرویس دلیوری/سالاد')),
                ('work_days', models.IntegerField(verbose_name='تعداد روز های کارکرد')),
                ('extra_shift_fee', models.IntegerField(verbose_name='مزد شیفت اضافه')),
                ('delivery_fee', models.IntegerField(verbose_name='حق پیک/سالاد')),
                ('off_days', models.IntegerField(verbose_name='ایام تعطیل کاری')),
                ('off_days_fee', models.IntegerField(verbose_name='مبلغ تعطیل کاری')),
                ('maskan_fee', models.IntegerField(verbose_name='حق مسکن')),
                ('childs_fee', models.IntegerField(verbose_name='حق اولاد')),
                ('bon_fee', models.IntegerField(verbose_name='بن')),
                ('years_fee', models.IntegerField(verbose_name='سنوات')),
                ('extra_hour_fee', models.IntegerField(verbose_name='مبلغ اضافه کاری')),
                ('salary_plus_mazaya', models.IntegerField(verbose_name='جمع حقوق و مزایا')),
                ('bime_fee', models.IntegerField(verbose_name='بیمه')),
                ('tax_fee', models.IntegerField(verbose_name='مالیات')),
                ('total_deduction', models.IntegerField(verbose_name='جمع کسورات')),
                ('payable_salary', models.IntegerField(verbose_name='حقوق پرداختنی')),
                ('karfarma_bime_share', models.IntegerField(verbose_name='بیمه حق کارفرما')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده'), ('paid', 'پرداخت شده'), ('pending', 'درانتظار پرداخت'), ('error', 'نقص مدارک')], default='registered', max_length=16, verbose_name='وضعیت حقوقی')),
                ('description', models.TextField(blank=True, max_length=128, null=True, verbose_name='توضیحات')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.BankAccount', verbose_name='حساب بانکی')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Salary', verbose_name='پرونده حقوق مربوطه')),
            ],
            options={
                'verbose_name': 'جزئیات حقوق',
                'verbose_name_plural': 'جزئیات حقوق ها',
                'permissions': (('can_see_salary_det', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='salarydetail',
            unique_together={('person', 'salary')},
        ),
    ]
