# Generated by Django 2.0.5 on 2018-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0022_auto_20180901_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarydetail',
            old_name='off_days',
            new_name='off',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bime_percentage',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bon_base',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='extra_percentage',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='kargar_bime_ratio1',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='maskan_base',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='tax_bime_ratio',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='tax_min',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='vezarat_kar_base',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='week_base',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='year_days',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bime_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bon_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='childs_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='extra_hour_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='extra_shift_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='karfarma_bime_share',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='maskan_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='off_days_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='payable_salary',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='salary_plus_mazaya',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='total_deduction',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='work_days',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='years_fee',
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bime_percentage',
            field=models.FloatField(default=7, verbose_name='درصد بیمه'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bon_base',
            field=models.IntegerField(default=1100000, verbose_name='پایه حق بن'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='days',
            field=models.IntegerField(default=0, verbose_name='تعداد روزهای کارکرد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='extra_percentage',
            field=models.FloatField(default=1.4, verbose_name='درصد اضافه کاری'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='kargar_bime_ratio1',
            field=models.FloatField(default=23, verbose_name='درصد حق کارگر در بیمه'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='maskan_base',
            field=models.IntegerField(default=400000, verbose_name='پایه حق مسکن'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='tax_bime_ratio',
            field=models.FloatField(default=0.28571429, verbose_name='کسر بیمه مالیات'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='tax_min',
            field=models.IntegerField(default=0, verbose_name='حداقل پایه حقوق برای محاسبه مالیات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='tax_percentage',
            field=models.IntegerField(default=10, verbose_name='درصد مالیات'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='week_base',
            field=models.IntegerField(default=220, verbose_name='حداقل ساعات کار ماهانه'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='base',
            field=models.IntegerField(verbose_name='حقوق پایه وزارت کار'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='fix',
            field=models.IntegerField(verbose_name='حقوق ثابت'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='help',
            field=models.IntegerField(verbose_name='مساعده'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='if_delivery_base',
            field=models.IntegerField(verbose_name='پایه حق سرویس دلیوری'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='if_delivery_count',
            field=models.IntegerField(verbose_name='تعداد دلیوری'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='mazaya',
            field=models.IntegerField(verbose_name='مزایای شغلی'),
        ),
    ]
