# Generated by Django 2.0.5 on 2018-09-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoFinance', '0011_auto_20180901_1205'),
        ('AmadoAccounting', '0023_auto_20180901_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان')),
                ('payment_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='توضیحات')),
                ('payment_date', django_jalali.db.models.jDateField(default='1397-06-10', verbose_name='تاریخ پرداخت')),
                ('payment_do_date', django_jalali.db.models.jDateField(default='1397-06-10', verbose_name='تاریخ اعمال')),
                ('payment_cost', models.IntegerField(verbose_name='مبلغ پرداختی(ریال)')),
                ('payment_add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('payment_confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_pay_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('payment_change_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تغییر')),
                ('payment_recede', models.ImageField(blank=True, null=True, upload_to='AmadoWH/static/HRFRecede', verbose_name='عکس رسید')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار پرداخت'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='registered', max_length=16, verbose_name='وضعیت پرداخت')),
                ('payment_account_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.BankAccount', verbose_name='حساب بانکی')),
                ('payment_add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrf_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('payment_change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrf_change_user', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('payment_confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrf_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('payment_pay_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrf_pay_user', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
                ('payment_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
            ],
            options={
                'verbose_name': 'مساعده/جریمه/پاداش',
                'verbose_name_plural': 'مساعده ها ...',
                'permissions': (('can_see_hrf', 'می تواند مشاهده کند'), ('can_confirm_hrf', 'می تواند تایید کند'), ('can_pay_hrf', 'می تواند پرداخت کند'), ('can_change_status_hrf', 'می تواند وضعیت را تغییر دهد')),
            },
        ),
    ]
