# Generated by Django 2.0.5 on 2018-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0024_employeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='childs',
            field=models.IntegerField(default=0, verbose_name='تعداد فرزندان'),
        ),
    ]
