# Generated by Django 2.0.5 on 2018-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0025_person_childs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='work_delivery_salad',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد پیک/سالاد'),
        ),
    ]
