# Generated by Django 2.0.5 on 2018-09-01 15:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0026_workdetail_work_delivery_salad'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='insurance_finish_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان بیمه'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع بیمه'),
        ),
    ]
