# Generated by Django 2.0.5 on 2018-09-01 15:11

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0027_auto_20180901_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default='1397-06-10', verbose_name='تاریخ توافق')),
                ('base', models.IntegerField(verbose_name='مبلغ توافقی')),
                ('two_shift', models.BooleanField(default=True, verbose_name='حضور دو شیفت')),
            ],
            options={
                'verbose_name': 'توافق حقوقی',
                'verbose_name_plural': 'توافقات حقوقی',
                'permissions': (('can_see_agreement', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='two_shift',
        ),
        migrations.AddField(
            model_name='baseagreement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد'),
        ),
    ]
