# Generated by Django 2.0.5 on 2018-09-01 15:21

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0028_auto_20180901_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default='1397-06-10', unique=True, verbose_name='تاریخ قانون')),
                ('vezarat_kar_base', models.IntegerField(default=11112690, verbose_name='حقوق پایه وزارت کار')),
                ('maskan_base', models.IntegerField(default=400000, verbose_name='پایه حق مسکن')),
                ('min_child', models.IntegerField(default=1, verbose_name='حداقل تعداد فرزند')),
                ('bon_base', models.IntegerField(default=1100000, verbose_name='پایه حق بن')),
                ('year_days', models.IntegerField(default=365, verbose_name='تعداد روزهای سال')),
                ('week_base', models.IntegerField(default=220, verbose_name='حداقل ساعات کار ماهانه')),
                ('extra_percentage', models.FloatField(default=1.4, verbose_name='درصد اضافه کاری')),
                ('bime_percentage', models.FloatField(default=7, verbose_name='درصد بیمه')),
                ('tax_bime_ratio', models.FloatField(default=0.28571429, verbose_name='کسر بیمه مالیات')),
                ('tax_percentage', models.IntegerField(default=10, verbose_name='درصد مالیات')),
                ('kargar_bime_ratio1', models.FloatField(default=23, verbose_name='درصد حق کارگر در بیمه')),
                ('tax_min', models.IntegerField(default=23000000, verbose_name='حداقل پایه حقوق برای محاسبه مالیات')),
                ('delivery_base', models.IntegerField(default=10000, verbose_name='پایه حق پیک')),
                ('salad_base', models.IntegerField(default=10000, verbose_name='پایه حق سالاد')),
            ],
            options={
                'verbose_name': 'ثابت حقوقی',
                'verbose_name_plural': 'ثابت های حقوقی',
                'permissions': (('can_see_lawconstant', 'می تواند مشاهده کند'),),
            },
        ),
    ]
