# Generated by Django 2.0.5 on 2018-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0029_lawconstant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='payment_type',
            field=models.CharField(choices=[('help', 'مساعده'), ('reward', 'پاداش'), ('fine', 'جریمه')], default='help', max_length=16, verbose_name='نوع'),
        ),
    ]
