# Generated by Django 2.0.5 on 2018-09-03 11:25

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoFinance', '0012_auto_20180903_1552'),
        ('AmadoAccounting', '0030_employeepayment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='base_on_2_shift',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bime_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='bon_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='extra_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='if_delivery_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='if_delivery_count',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='kargar_bime_ratio1',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='maskan_base',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_bime_ratio',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_min',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='week_base',
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.BankAccount', verbose_name='حساب بانکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='agreement',
            field=models.IntegerField(default=12000000, verbose_name='پایه حقوق توافقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bime',
            field=models.IntegerField(default=1, verbose_name='بیمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='bon',
            field=models.IntegerField(default=1, verbose_name='بن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='childs_money',
            field=models.IntegerField(default=1, verbose_name='حق اولاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='del_sal',
            field=models.IntegerField(default=1, verbose_name='حق پیک/سالاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='extra_hours_fee',
            field=models.IntegerField(default=1, verbose_name='مبلغ اضافه کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='extra_shift_fee',
            field=models.IntegerField(default=1, verbose_name='مزد شیفت اضافه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='fine',
            field=models.IntegerField(default=1, verbose_name='جریمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='hoghoogh_mazaya_plus',
            field=models.IntegerField(default=1, verbose_name='جمع حقوق و مزایا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='hoghoogh_vezarat_kar_tot',
            field=models.IntegerField(default=1, verbose_name='جمع حقوق وزارت کار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='karfarma_bime',
            field=models.IntegerField(default=1, verbose_name='بیمه سهم کارفرما'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='kosoorat_sum',
            field=models.IntegerField(default=1, verbose_name='جمع کسورات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='maliat',
            field=models.IntegerField(default=1, verbose_name='مالیات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='maskan',
            field=models.IntegerField(default=1, verbose_name='حق مسکن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='negative_taraz',
            field=models.IntegerField(default=1, verbose_name='تراز منفی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='off_fee',
            field=models.IntegerField(default=1, verbose_name='مبلغ تعطیل کاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='other_deduction',
            field=models.IntegerField(default=1, verbose_name='سایر کسورات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='pardakhti',
            field=models.IntegerField(default=1, verbose_name='حقوق پرداختی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='positive_taraz',
            field=models.IntegerField(default=1, verbose_name='تراز مثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='reward',
            field=models.IntegerField(default=1, verbose_name='پاداش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='sanavat',
            field=models.IntegerField(default=1, verbose_name='سنوات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='snapp',
            field=models.IntegerField(default=1, verbose_name='حق اسنپ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseagreement',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-12', verbose_name='تاریخ توافق'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-06-12', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-06-12', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-12', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='base',
            field=models.IntegerField(verbose_name='حقوق پایه'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='extra_hours',
            field=models.IntegerField(verbose_name='ساعت اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-12', verbose_name='تاریخ'),
        ),
    ]
