# Generated by Django 2.0.5 on 2018-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0031_auto_20180903_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='description',
            field=models.TextField(default=1, max_length=512, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
