# Generated by Django 2.0.5 on 2018-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0032_salarydetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='del_sal_fee',
            field=models.IntegerField(default=1, verbose_name='حق پیک/سالاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='del_sal',
            field=models.IntegerField(verbose_name='پیک/سالاد'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='توضیحات'),
        ),
    ]
