# Generated by Django 2.0.5 on 2018-09-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0033_auto_20180903_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='status',
        ),
    ]
