# Generated by Django 2.0.5 on 2018-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0035_auto_20180903_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='bime',
            field=models.IntegerField(blank=True, null=True, verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='extra_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='fine',
            field=models.IntegerField(blank=True, null=True, verbose_name='جریمه'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='help',
            field=models.IntegerField(blank=True, null=True, verbose_name='مساعده'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='maliat',
            field=models.IntegerField(blank=True, null=True, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='mazaya',
            field=models.IntegerField(blank=True, null=True, verbose_name='مزایای شغلی'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='other_deduction',
            field=models.IntegerField(blank=True, null=True, verbose_name='سایر کسورات'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='reward',
            field=models.IntegerField(blank=True, null=True, verbose_name='پاداش'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='snapp',
            field=models.IntegerField(blank=True, null=True, verbose_name='حق اسنپ'),
        ),
    ]
