# Generated by Django 2.0.5 on 2018-09-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0036_auto_20180903_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='salarydetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='account',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='confirm_user',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='person',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='salary',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='SalaryDetail',
        ),
    ]
