# Generated by Django 2.0.5 on 2018-09-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoWHApp', '0068_auto_20180903_2021'),
        ('AmadoFinance', '0012_auto_20180903_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AmadoAccounting', '0037_auto_20180903_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', django_jalali.db.models.jDateField(verbose_name='ماه')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق ها',
                'permissions': (('can_see_salary', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name='تعداد روزهای کارکرد')),
                ('fix', models.IntegerField(verbose_name='حقوق ثابت')),
                ('base', models.IntegerField(verbose_name='حقوق پایه')),
                ('agreement', models.IntegerField(verbose_name='پایه حقوق توافقی')),
                ('maskan', models.IntegerField(verbose_name='حق مسکن')),
                ('childs', models.IntegerField(verbose_name='تعداد فرزند')),
                ('childs_money', models.IntegerField(verbose_name='حق اولاد')),
                ('bon', models.IntegerField(verbose_name='بن')),
                ('sanavat', models.IntegerField(verbose_name='سنوات')),
                ('hoghoogh_vezarat_kar_tot', models.IntegerField(verbose_name='جمع حقوق وزارت کار')),
                ('positive_taraz', models.IntegerField(verbose_name='تراز مثبت')),
                ('mazaya', models.IntegerField(blank=True, null=True, verbose_name='مزایای شغلی')),
                ('extra_shift', models.IntegerField(verbose_name='شیفت اضافه')),
                ('extra_shift_fee', models.IntegerField(verbose_name='مزد شیفت اضافه')),
                ('del_sal', models.IntegerField(verbose_name='پیک/سالاد')),
                ('del_sal_fee', models.IntegerField(verbose_name='حق پیک/سالاد')),
                ('off', models.IntegerField(verbose_name='ایام تعطیل کاری')),
                ('off_fee', models.IntegerField(verbose_name='مبلغ تعطیل کاری')),
                ('extra_hours', models.IntegerField(blank=True, null=True, verbose_name='ساعت اضافه کاری')),
                ('extra_hours_fee', models.IntegerField(verbose_name='مبلغ اضافه کاری')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='پاداش')),
                ('snapp', models.IntegerField(blank=True, null=True, verbose_name='حق اسنپ')),
                ('hoghoogh_mazaya_plus', models.IntegerField(verbose_name='جمع حقوق و مزایا')),
                ('help', models.IntegerField(blank=True, null=True, verbose_name='مساعده')),
                ('negative_taraz', models.IntegerField(verbose_name='تراز منفی')),
                ('other_deduction', models.IntegerField(blank=True, null=True, verbose_name='سایر کسورات')),
                ('fine', models.IntegerField(blank=True, null=True, verbose_name='جریمه')),
                ('bime', models.IntegerField(blank=True, null=True, verbose_name='بیمه')),
                ('maliat', models.IntegerField(blank=True, null=True, verbose_name='مالیات')),
                ('kosoorat_sum', models.IntegerField(verbose_name='جمع کسورات')),
                ('pardakhti', models.IntegerField(verbose_name='حقوق پرداختی')),
                ('karfarma_bime', models.IntegerField(verbose_name='بیمه سهم کارفرما')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='توضیحات')),
                ('payment_status', models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده/در انتظار امضای تسویه'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('error', 'نقص مدارک')], default='registered', max_length=16, verbose_name='وضعیت حقوقی')),
                ('add_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ ثبت')),
                ('confirm_date', django_jalali.db.models.jDateTimeField(default='1397-03-28 20:38:00', verbose_name='تاریخ تایید')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoFinance.BankAccount', verbose_name='حساب بانکی')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_register_user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Person', verbose_name='فرد')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadoAccounting.Salary', verbose_name='پرونده حقوق مربوطه')),
            ],
            options={
                'verbose_name': 'جزئیات حقوق',
                'verbose_name_plural': 'جزئیات حقوق ها',
                'permissions': (('can_see_salary_det', 'می تواند مشاهده کند'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='salarydetail',
            unique_together={('person', 'salary')},
        ),
    ]
