# Generated by Django 2.0.5 on 2018-09-05 11:16

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0039_auto_20180903_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseagreement',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-14', verbose_name='تاریخ توافق'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_cost',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مبلغ پرداختی(ریال)'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-06-14', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-06-14', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_type',
            field=models.CharField(choices=[('help', 'مساعده'), ('reward', 'پاداش'), ('fine', 'جریمه'), ('other', 'سایر کسورات'), ('otherm', 'سایر مزایا'), ('snapp', 'حق اسنپ')], default='help', max_length=16, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-14', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-14', verbose_name='تاریخ'),
        ),
    ]
