# Generated by Django 2.0.5 on 2018-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0041_auto_20180906_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseagreement',
            name='snapp_fee',
            field=models.IntegerField(default=0, verbose_name='حق اسنپ'),
        ),
    ]
