# Generated by Django 2.0.5 on 2018-09-07 08:56

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0043_auto_20180906_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseagreement',
            name='snapp_fee',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='vacation_rem',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='vacation_rem_fee',
        ),
        migrations.AlterField(
            model_name='baseagreement',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-16', verbose_name='تاریخ توافق'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-06-16', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-06-16', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-16', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadoWHApp.Branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-16', verbose_name='تاریخ'),
        ),
    ]
