# Generated by Django 2.0.5 on 2018-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0044_auto_20180907_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseagreement',
            name='snapp_fee',
            field=models.IntegerField(default=0, verbose_name='حق اسنپ'),
        ),
    ]
