# Generated by Django 2.0.5 on 2018-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0045_baseagreement_snapp_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='eydi',
            field=models.IntegerField(default=0, verbose_name='عیدی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='vacation_rem',
            field=models.IntegerField(default=0, verbose_name='مرخصی نرفته'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='vacation_rem_fee',
            field=models.IntegerField(default=0, verbose_name='حق طلب مرخصی'),
            preserve_default=False,
        ),
    ]
