# Generated by Django 2.0.5 on 2018-09-09 17:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0046_auto_20180907_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='from_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='از تاریخ'),
        ),
        migrations.AddField(
            model_name='salary',
            name='to_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='baseagreement',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-18', verbose_name='تاریخ توافق'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-06-18', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-06-18', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-18', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-06-18', verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='work_status',
            field=models.CharField(choices=[('P', 'حضور یک شیفت'), ('PP', 'حضور دو شیفت'), ('V', 'مرخصی'), ('T', 'ترانسفر'), ('O', 'آف'), ('A', 'غیبت'), ('Q', 'استعفا')], default='P', max_length=16, verbose_name='وضعیت حضور'),
        ),
    ]
