# Generated by Django 2.0.5 on 2018-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0051_auto_20180926_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_direct',
            field=models.BooleanField(default=True, verbose_name='نقش اثر مستقیم روی محصولات بخش مربوطه دارد'),
        ),
    ]
