# Generated by Django 2.0.5 on 2018-09-30 16:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0053_auto_20180929_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepayment',
            options={'permissions': (('can_see_hrf', 'می تواند مشاهده کند'), ('can_confirm_hrf', 'می تواند تایید کند'), ('can_pay_hrf', 'می تواند پرداخت کند'), ('can_change_status_hrf', 'می تواند وضعیت را تغییر دهد')), 'verbose_name': 'مساعده/جریمه/پاداش', 'verbose_name_plural': 'مساعده ها / جریمه ها / پاداش ها ...'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_direct',
        ),
        migrations.AlterField(
            model_name='baseagreement',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-05-01', verbose_name='تاریخ توافق'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-07-08', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-07-08', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_recede',
            field=models.ImageField(blank=True, null=True, upload_to='AmadoWH/static/HRFRecede', verbose_name='فایل رسید'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-07-08', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='agreement',
            field=models.IntegerField(verbose_name='حقوق توافقی دوره'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='base',
            field=models.IntegerField(verbose_name='حقوق پایه دوره'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-07-08', verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت شده/در انتظار تایید'), ('confirmed', 'تایید شده')], default='confirmed', max_length=16, verbose_name='وضعیت'),
        ),
    ]
