# Generated by Django 2.1.2 on 2018-10-29 06:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadoAccounting', '0056_auto_20181010_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment_do_date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ اعمال'),
        ),
        migrations.AlterField(
            model_name='lawconstant',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', unique=True, verbose_name='تاریخ قانون'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=django_jalali.db.models.jDateField(default='1397-08-07', verbose_name='تاریخ'),
        ),
    ]
